#define Y_INTERCEPT_CLASSIFIER_CONSTANT 0.01f
#define SLOPE_CLASSIFIER_CONSTANT 0.01f
#define EPSILON 0.001f
#define LEARNING_RATE 0.01f
#define MAX_CLASSIFIER_ITERATIONS 100
#define CROSS_BOUNDARY_LINE_PENALTY 5
#define MAX_SEARCH_LAYERS 5 //MUST BE 2 OR HIGHER
#define ABS(x) ((x) < 0) ? -(x) : x 
